version: "3.8"

services:
  drupal:
    build:
      context: .
      args:
        PROJECT: ${PROJECT}
    volumes:
      - ./:/var/www/${PROJECT}
      - ./000-default.conf:/etc/apache/sites-available/000-default.conf
    ports:
      - "80:80"

  database:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes

  bootstrap:
    command: composer create-project drupal/recommended-project:10.1.6 /tmp/${PROJECT} && cp -r /tmp/${PROJECT}/* .
    build:
      context: .
      args:
        PROJECT: ${PROJECT}
    volumes:
      - ./:/var/www/${PROJECT}
    profiles:
      - bootstrap
